# Generated by Django 5.1.1 on 2024-12-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
    ]
