# Generated by Django 5.1.1 on 2024-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movies_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=100, verbose_name='導演'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_description',
            field=models.TextField(blank=True, null=True, verbose_name='電影描述'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(max_length=100, verbose_name='電影類型'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(max_length=255, verbose_name='電影名稱'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='電影海報'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(verbose_name='上映日期'),
        ),
    ]
