# Generated by Django 5.1.1 on 2024-12-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_remove_movies_cast_remove_movies_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.TextField(blank=True, default='未知演員', null=True, verbose_name='主要演員'),
        ),
    ]
