# Generated by Django 5.0.7 on 2025-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbNeedImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'db_need_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbNeedInfo',
            fields=[
                ('needer_id', models.IntegerField()),
                ('needer_nickname', models.CharField(max_length=50)),
                ('needer_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('needer_introduction', models.CharField(blank=True, max_length=300, null=True)),
                ('need_id', models.AutoField(primary_key=True, serialize=False)),
                ('need_title', models.CharField(blank=True, max_length=50, null=True)),
                ('need_category', models.CharField(blank=True, max_length=50, null=True)),
                ('need_original_from', models.CharField(blank=True, max_length=150, null=True)),
                ('need_description', models.TextField(blank=True, null=True)),
                ('need_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('need_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'db_need_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbPublicCard',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_avatar', models.CharField(max_length=255)),
                ('user_introduction', models.CharField(blank=True, max_length=300, null=True)),
                ('involved_works', models.TextField(blank=True, null=True)),
                ('key_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('price_list', models.TextField(blank=True, null=True)),
                ('price_example_image', models.CharField(blank=True, max_length=255, null=True)),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('work_title', models.CharField(blank=True, max_length=50, null=True)),
                ('work_original_from', models.CharField(blank=True, max_length=150, null=True)),
                ('work_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('need_id', models.IntegerField(blank=True, null=True)),
                ('need_title', models.CharField(blank=True, max_length=50, null=True)),
                ('need_original_from', models.CharField(blank=True, max_length=150, null=True)),
                ('need_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('reviewer_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('deal_count', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_public_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbWorksInfo',
            fields=[
                ('author_id', models.IntegerField()),
                ('author_nickname', models.CharField(max_length=50)),
                ('author_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('author_introduction', models.CharField(blank=True, max_length=300, null=True)),
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_title', models.CharField(blank=True, max_length=50, null=True)),
                ('work_original_from', models.CharField(blank=True, max_length=150, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('usage_restrictions', models.TextField(blank=True, null=True)),
                ('sale_items', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('work_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('original_file', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_history', models.TextField(blank=True, null=True)),
                ('work_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('work_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('work_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'db_works_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberBasic',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(max_length=120, unique=True)),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user_birth', models.DateField(blank=True, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('vip_status', models.IntegerField(blank=True, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=50, null=True)),
                ('privacy_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberPrivacy',
            fields=[
                ('privacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=120, null=True)),
                ('privacy_name', models.CharField(blank=True, max_length=50, null=True)),
                ('privacy_value', models.IntegerField(blank=True, null=True)),
                ('phone_change', models.CharField(blank=True, max_length=10, null=True)),
                ('email_change', models.CharField(blank=True, max_length=50, null=True)),
                ('account_verify', models.IntegerField(blank=True, null=True)),
                ('activity_checked', models.IntegerField(blank=True, null=True)),
                ('double_verify', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_privacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberVerify',
            fields=[
                ('verify_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=16, null=True)),
                ('code_used', models.IntegerField(blank=True, null=True)),
                ('token_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_verify',
                'managed': False,
            },
        ),
    ]
