# Generated by Django 5.0.7 on 2024-12-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productwishlist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='productbrands',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcomments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productrecommendations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productreviews',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productseries',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='MemberFavorites',
        ),
        migrations.DeleteModel(
            name='ProductWishlist',
        ),
    ]
