# Generated by Django 5.1.1 on 2024-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_title', models.CharField(max_length=255)),
                ('game_description', models.TextField()),
                ('game_genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('game_platform', models.CharField(max_length=100)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
    ]
