"""
Django settings for ACGN_Project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv
load_dotenv()

# 從環境變數獲取 API 金鑰
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY') 
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY') 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-64^zt5vic77!oee7ka%^si0%0c3-&j5r#cb0)4=2@*&d(h1%4h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'cart_api',
    'products',
    'products_backend',
    'users',        # 顯示 後端管理者頁面-member      
    'users_api',    # 串接 後端管理者介面-member
    'admins',       # 顯示 後端管理者頁面-admin
    'admins_api',   # 串接 後端管理者介面-admin
    'member_api',   # 串接 前端Vue-member
    'promotions',
    'commission',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'Games',
    'Movies',
    'Animations',
    'Discussion_board',
    'discussion',
    'entertainment',
]

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,                  # 是否在每次刷新時更新 Refresh Token
    'BLACKLIST_AFTER_ROTATION': True,               # 是否將舊的 Refresh Token 加入黑名單
    'USER_ID_FIELD': 'user_id',                      # 使用 user_id 作為主鍵
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',   # 要在 template 用到 MEDIA_URL
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Cache 配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # 'BACKEND': 'django_redis.cache.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
        # 'OPTIONS': {
        #     'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        # }
    }
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shopping', #資料庫名稱
        'USER': 'root', #登入資料庫的帳號
        'PASSWORD': 'P@ssw0rd', #登入資料庫帳號的密碼
        'HOST':'localhost', #MySQL所在位置，localhost表示本機
        'PORT':3306, #MySQL所在位置的Port號
        'OPTIONS': {
            'charset': 'utf8mb4'
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR/'static']

STATIC_URL = 'assets/'
STATICFILES_DIRS = [BASE_DIR/'assets']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 上傳檔案
MEDIA_URL = '/media/'  #路徑名稱
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#  設置允許上傳的文件大小不超過限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Email寄送    SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  #SMTP伺服器
EMAIL_PORT = 465  #TLS通訊埠號
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'forworkjayjay@gmail.com'  #寄件者電子郵件
# EMAIL_HOST_PASSWORD = 'uyvj optv xzuc qrfs'  #Gmail應用程式的密碼(before)
EMAIL_HOST_PASSWORD = 'kaoe tpvv qsbm kiaq'  #Gmail應用程式的密碼(after)

# 網站URL
SITE_URL = 'http://127.0.0.1:8000'  # 開發環境
# SITE_URL = 'https://your-production-domain.com'  # 生產環境

# 定向用戶到前端
FRONTEND_URL = "http://localhost:5173/"

# 定向LINE相關到前端
LINE_CLIENT_ID = "2006769537"
LINE_CLIENT_SECRET = "c77386e6e4b34536a694db28767d6998"
LINE_REDIRECT_URI = "http://localhost:5173/verify-line/"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True