# Generated by Django 5.1.1 on 2024-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('animation_id', models.AutoField(primary_key=True, serialize=False)),
                ('animation_title', models.CharField(max_length=255)),
                ('animation_description', models.TextField()),
                ('episodes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('animation_genre', models.CharField(max_length=100)),
                ('animation_studio', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'animations',
                'managed': False,
            },
        ),
    ]
