# Generated by Django 5.1.4 on 2024-12-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBasic',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(max_length=120, unique=True)),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=17, null=True)),
                ('user_birth', models.DateField(blank=True, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('vip_status', models.IntegerField(blank=True, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_basic',
            },
        ),
        migrations.CreateModel(
            name='MemberPhotos',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.memberbasic')),
            ],
            options={
                'db_table': 'member_photos',
            },
        ),
        migrations.CreateModel(
            name='MemberPrivacy',
            fields=[
                ('privacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_verified', models.IntegerField(blank=True, null=True)),
                ('email_verified', models.IntegerField(blank=True, null=True)),
                ('account_verify', models.IntegerField(blank=True, null=True)),
                ('activity_checked', models.IntegerField(blank=True, null=True)),
                ('double_verify', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.memberbasic')),
            ],
            options={
                'db_table': 'member_privacy',
            },
        ),
        migrations.CreateModel(
            name='MemberVerify',
            fields=[
                ('verify_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_value', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_code', models.CharField(max_length=6)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('verification_type', models.CharField(max_length=15)),
                ('code_used', models.IntegerField(blank=True, null=True)),
                ('token_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.memberbasic')),
            ],
            options={
                'db_table': 'member_verify',
            },
        ),
    ]
